version: "3"
services:
  redis:
    image: redis:alpine
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role == worker]
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints: [node.role == worker]
  frontend-ovoz:
    image: feruzjon/ovoz:latest
    ports:
      - "5000:80"
    networks:
      - frontend
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
  frontend-natija:
    image: feruzjon/natija:latest
    ports:
      - "5001:80"
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == worker]
  backend:
    image: feruzjon/backend:latest
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
networks:
  frontend:
  backend:
volumes:
  db_data:
    driver: local
